name: Deploy Documentation
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install help2man
    - name: Get crosstool-NG
      run: ./.github/scripts/ct-ng.sh
    - name: Test path
      run: echo "$PATH"
    - name: Build linux
      run: ./.github/scripts/build-linux.sh
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: root.tar
        path: linux-build/root