name: Build Linux image

on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: avr-build:latest
          outputs: type=docker,dest=/tmp/avr-build.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: avr-build
          path: /tmp/avr-build.tar
          retention-days: 1
  build-linux:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: avr-build
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/avr-build.tar
          rm /tmp/avr-build.tar
      
      - name: build-linux
        run : |
          docker run -t avr-build:latest --mount type=bind,src=/tmp/out,dst=/out sh linux.sh
          ls /tmp/out

      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: root
          path: /tmp/out/root

      - name: Upload windows base root
        uses: actions/upload-artifact@v4
        with:
          name: baseroot
          path: /tmp/out/baseroot

